services:
  aivg:
    pull_policy: build
    build:
      dockerfile: Dockerfile.aivg
    container_name: aivg
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    ports:
      - "5661:5661"
    depends_on:
      aivg-fp-studio:
        condition: service_healthy
      aivg-fooocus-api:
        condition: service_healthy
      #aivg-mmaudio:
      #  condition: service_healthy
      aivg-ollama:
        condition: service_healthy
      aivg-anythingllm:
        condition: service_healthy
    volumes:
      - ".env:/app/.env"
      - "/mnt/d/generated:/app/outputs"
    image: "blastbeng/aivg:1.0.0"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5661"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  #aivg-nginx:
  #  image: lscr.io/linuxserver/nginx:latest
  #  container_name: aivg-nginx
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Europe/Rome
  #  volumes:
  #    - ./nginx:/config
  #    - "/mnt/d/generated:/app/www/public"
  #  ports:
  #    - 5662:5662
  #  restart: unless-stopped
  aivg-fp-studio:
    build:
      args:
        - CUDA_VERSION=12.8.1
      dockerfile: Dockerfile.framepack-studio
    pull_policy: build
    container_name: aivg-fp-studio
    image: blastbeng/aivg-fp-studio:1.0.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "7860:7860"
    volumes:
    #  - "./framepack-studio/loras:/app/loras"
      - "$HOME/.cache/huggingface/hub/models--Kijai--HunyuanVideo_comfy/snapshots/b0bb3f4f83cbdce6d2c11c6db7d527749ae75c05:/app/loras"
    #  - "./framepack-studio/outputs:/app/outputs"
      - "/mnt/d/generated:/app/outputs"
      - "./.framepack:/app/.framepack"
      - "./modules/toolbox/model_gfpgan:/app/modules/toolbox/model_gfpgan"
      - "./modules/toolbox/model_esrgan:/app/modules/toolbox/model_esrgan"
      - "./modules/toolbox/model_rife:/app/modules/toolbox/model_rife"
      - "./modules/toolbox/bin:/app/modules/toolbox/bin"
      - "$HOME/.cache/huggingface:/app/hf_download"
      - gfpgan_weights:/app/gfpgan/weights
    runtime: "nvidia"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7860"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  aivg-fooocus-api:
    image: blastbeng/aivg-fooocus-api:1.0.0
    container_name: aivg-fooocus-api
    build:
      dockerfile: Dockerfile.fooocus-api
    pull_policy: build
    ports:
      - "8888:8888"
    volumes:
      - ./Fooocus/models:/app/repositories/Fooocus/models
      - ./.cache/pip:/root/.cache/pip
    runtime: "nvidia"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8888"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  aivg-mmaudio-api:
    build:
      args:
        - CUDA_VERSION=12.8.1
      dockerfile: Dockerfile.mmaudio-api
    image: blastbeng/aivg-mmaudio-api:1.0.0
    container_name: aivg-mmaudio-api
    ports:
      - "8000:8000"
    volumes:
      - weights:/app/weights
      - ext_weights:/app/ext_weights
      - huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      # Increase timeout for synchronous processing
      - UVICORN_TIMEOUT=3600
      - TORCH_USE_INFERENCE_MODE=1
    restart: unless-stopped
    runtime: "nvidia"
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "http://127.0.0.1:8000/process"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  aivg-anythingllm:
    image: mintplexlabs/anythingllm
    container_name: aivg-anythingllm
    pull_policy: always
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=${ANYTHING_LLM_JWT_SECRET}
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://172.17.0.1:11435
      - OLLAMA_MODEL_PREF=huihui_ai/granite3.2-abliterated:latest
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://172.17.0.1:11435
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
    volumes:
      - ./storage:/app/server/storage
    restart: unless-stopped
    depends_on:
      aivg-ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3001"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  aivg-ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: aivg-ollama
    pull_policy: always
    tty: true
    ports:
      - "11435:11435"
    restart: unless-stopped
    image: docker.io/ollama/ollama:latest
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11435
    healthcheck:
      test: kill -0 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
    runtime: "nvidia"
networks:
  aivg_network:
    driver: bridge
volumes:
  fooocus-data:
  weights:
  ext_weights:
  huggingface:
  gfpgan_weights:
