services:
  aivg:
    pull_policy: build
    build:
      dockerfile: Dockerfile.aivg
    container_name: aivg
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - MODE="WAN2GP"
    ports:
      - "5661:5661"
    depends_on:
      aivg-wan2gp:
        condition: service_healthy
      aivg-fooocus-api:
        condition: service_healthy
      aivg-ollama:
        condition: service_healthy
      aivg-anythingllm:
        condition: service_healthy
    volumes:
      - ".env:/app/.env"
      - "./outputs:/app/outputs"
    #  - "/mnt/d/generated:/app/outputs"
    image: "blastbeng/aivg:1.0.0"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5661"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
    entrypoint: ["./entrypoint-wan2gp.sh"]
  #aivg-nginx:
  #  image: lscr.io/linuxserver/nginx:latest
  #  container_name: aivg-nginx
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Europe/Rome
  #  volumes:
  #    - ./nginx:/config
  #    - "/mnt/d/generated:/app/www/public"
  #  ports:
  #    - 5662:5662
  #  restart: unless-stopped
  aivg-wan2gp:
    build:
      args:
        - CUDA_VERSION=12.8.1
      dockerfile: Dockerfile.wan2gp
    pull_policy: build
    container_name: aivg-wan2gp
    image: blastbeng/aivg-wan2gp:1.0.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_NAME=0.0.0.0
      - SERVER_PORT=7862
    ports:
      - "7862:7862"
    volumes:      
      - "$HOME/.cache/huggingface:/app/hf_download"
      - "$HOME/.cache/huggingface:/root/.cache/huggingface"
      - ./Wan2GP/configs:/app/configs
      - ./Wan2GP/loras:/app/loras
      - ./Wan2GP/loras_flux:/app/loras_flux
      - ./Wan2GP/loras_hunyuan:/app/loras_hunyuan
      - ./Wan2GP/loras_hunyuan_i2v:/app/loras_hunyuan_i2v
      - ./Wan2GP/loras_i2v:/app/loras_i2v
      - ./Wan2GP/loras_ltxv:/app/loras_ltxv
      - ./Wan2GP/loras_qwen:/app/loras_qwen
      - ./Wan2GP/ckpts:/app/ckpts
      - "./outputs:/app/outputs"
      - "./wgp_config.json:/app/wgp_config.json"
    runtime: "nvidia"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7862"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  aivg-fooocus-api:
    image: blastbeng/aivg-fooocus-api:1.0.0
    container_name: aivg-fooocus-api
    build:
      dockerfile: Dockerfile.fooocus-api
    pull_policy: build
    ports:
      - "8888:8888"
    volumes:
      - ./Fooocus/models:/app/repositories/Fooocus/models
      - ./.cache/pip:/root/.cache/pip
    runtime: "nvidia"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8888"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  aivg-anythingllm:
    image: mintplexlabs/anythingllm
    container_name: aivg-anythingllm
    pull_policy: always
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=${ANYTHING_LLM_JWT_SECRET}
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://172.17.0.1:11435
      - OLLAMA_MODEL_PREF=huihui_ai/granite3.2-abliterated:latest
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://172.17.0.1:11435
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
    volumes:
      - ./storage:/app/server/storage
    restart: unless-stopped
    depends_on:
      aivg-ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3001"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
  aivg-ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: aivg-ollama
    pull_policy: always
    tty: true
    ports:
      - "11435:11435"
    restart: unless-stopped
    image: docker.io/ollama/ollama:latest
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11435
    healthcheck:
      test: kill -0 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - aivg_network
    runtime: "nvidia"
networks:
  aivg_network:
    driver: bridge
volumes:
  fooocus-data:
