#!/bin/sh
hf download Kijai/HunyuanVideo_comfy hyvideo_FastVideo_LoRA-fp8.safetensors
hf download Kijai/HunyuanVideo_comfy hunyuan_video_accvid_5_steps_lora_rank16_fp8_e4m3fn.safetensors
hf download Kijai/HunyuanVideo_comfy hunyuan_video_FastVideo_720_fp8_e4m3fn.safetensors
hf download Kijai/HunyuanVideo_comfy hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors
hf download Kijai/HunyuanVideo_comfy hyvid_I2V_lora_embrace.safetensors
hf download Kijai/HunyuanVideo_comfy hyvid_I2V_lora_hair_growth.safetensors

